"""Added worker model, added one-to-many relation (hours)

Revision ID: 088060656eec
Revises: 691398a91954
Create Date: 2021-01-05 09:34:06.564155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "088060656eec"
down_revision = "691398a91954"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "worker",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("total_hours_off_a_year", sa.Float(), nullable=False),
        sa.Column("total_hours_in_one_full_workday", sa.Float(), nullable=False),
        sa.Column("extra_minutes_left_from_last_year", sa.Integer()),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("employee", sa.Column("worker_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "employee", "worker", ["worker_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "employee", type_="foreignkey")
    op.drop_column("employee", "worker_id")
    op.drop_table("worker")
    # ### end Alembic commands ###
