"""Readd extra_hours column

Revision ID: 0c69d46da484
Revises: 490b24461b76
Create Date: 2020-10-08 20:51:12.102824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c69d46da484'
down_revision = '490b24461b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('extra_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'extra_hours')
    # ### end Alembic commands ###
