"""Added function to User model

Revision ID: 170dfdd31d63
Revises: 74a7899505cc
Create Date: 2020-11-05 17:04:12.945436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170dfdd31d63'
down_revision = '74a7899505cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('function', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'function')
    # ### end Alembic commands ###
