"""Made character limitation for Remarks / toestellen bigger

Revision ID: 37e3a9361efb
Revises: 170dfdd31d63
Create Date: 2020-11-06 19:24:51.209811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e3a9361efb'
down_revision = '170dfdd31d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('arctic_sun', 'remarks',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('arctic_sun', 'remarks',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
