"""Remove extra_hours column

Revision ID: 490b24461b76
Revises: 5ebbf4000544
Create Date: 2020-10-08 20:45:49.819163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490b24461b76'
down_revision = '5ebbf4000544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'extra_hours')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('extra_hours', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
