"""Add Unique Constraint employee-workday

Revision ID: 5ebbf4000544
Revises: c0ff2dba6456
Create Date: 2020-10-08 20:39:43.003224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ebbf4000544'
down_revision = 'c0ff2dba6456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_personid_workday', 'employee', ['person_id', 'workday'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_personid_workday', 'employee', type_='unique')
    # ### end Alembic commands ###
