"""Added column for soft-deletes at Card model

Revision ID: 691398a91954
Revises: 04dca3cd85ba
Create Date: 2020-11-07 15:44:45.785050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691398a91954'
down_revision = '04dca3cd85ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'deleted_at')
    # ### end Alembic commands ###
