"""User - firm added in db

Revision ID: 74a7899505cc
Revises: 0c69d46da484
Create Date: 2020-10-15 18:53:43.965256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a7899505cc'
down_revision = '0c69d46da484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firm', sa.String(length=60)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'firm')
    # ### end Alembic commands ###
