"""Initial migration.

Revision ID: 99888400f6ad
Revises: 
Create Date: 2020-08-19 20:21:27.844791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99888400f6ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arctic_sun', sa.Column('remarks', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arctic_sun', 'remarks')
    # ### end Alembic commands ###
