"""db type added to ArcticSun model

Revision ID: c0ff2dba6456
Revises: c652ec160e90
Create Date: 2020-09-13 15:43:55.727930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ff2dba6456'
down_revision = 'c652ec160e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arctic_sun', sa.Column('type', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arctic_sun', 'type')
    # ### end Alembic commands ###
